---
title: "Data Preparation"
params:
  out_dir: "processed/train"
  x_path: "/Users/app/Desktop/RemoteSensingPresentation/tiff_vrt/region-corrected.vrt" ##with corrected vrt file
  #x_path: "/Users/app/Desktop/RemoteSensingPresentation/tiff_vrt/region (1).vrt"
  y_path: "/Users/app/Desktop/RemoteSensingPresentation/vector_data/glaciers.geojson"
  basins: "/Users/app/Desktop/RemoteSensingPresentation/Index/train_list-small (1).csv"
  n_patches: 200
  #basins: "https://uwmadison.box.com/shared/static/iilcsf3bbois8tmt7pklriu219s4wlu6.csv" # for test basins
  B: 1
---

```{r setup, include=FALSE}
#new vrt only 11 layers
rm(list=setdiff(ls(), "params"))
knitr::opts_chunk$set(echo = TRUE, cache = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library("RStoolbox")
library("abind")
library("dplyr")
library("gdalUtils")
library("ggplot2")
library("gridExtra")
library("purrr")
library("raster")
library("readr")
library("reticulate")
library("sf")
library("stringr")
library("tidyr")

# setting up python environment
use_condaenv("mappingvis")
np <- import("numpy")
source("data.R")
theme_set(theme_minimal())
set.seed(params$B)
```

Read geojson.

```{r}
y_path <- file.path(params$y_path)
basins <- read_csv(params$basins)
x_path<-file.path(params$x_path)
y <- read_sf(y_path) %>%
  filter(Sub_basin %in% basins$Sub_basin)
```

Get sampling locations.

```{r}
centers <- y %>%
  st_sample(params$n_patches, type = "random", by_polygon = FALSE) %>%
  st_coordinates()
```


```{r}
vrt_path <- file.path(params$x_path)
ys <- y %>% split(.$Glaciers)
```


Write all results.

```{r}
write_patches(vrt_path, ys, centers, params$out_dir)
centers<-cbind(centers,c(1:params$n_patches))
colnames(centers)<-c("Longitude","Latitude","ID")
write.csv(centers,file.path(params$out_dir, paste0("centers-", params$B, ".csv")))

```
